"""Add features column to Plano model

Revision ID: 34233a45308b
Revises: 463b9f95b703
Create Date: 2024-11-12 23:47:15.132116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34233a45308b'
down_revision = '463b9f95b703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.PickleType(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.drop_column('features')

    # ### end Alembic commands ###
