"""empty message

Revision ID: 463b9f95b703
Revises: 116feb535366
Create Date: 2024-11-12 21:53:26.214192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '463b9f95b703'
down_revision = '116feb535366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=18),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
