"""Recriação do esquema de tabelas

Revision ID: 48fbcae51f54
Revises: 
Create Date: 2024-11-10 20:43:49.950370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48fbcae51f54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato', sa.String(length=50), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('endereco',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_constraint('oficina_ibfk_1', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('marca',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('modelo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('ano_fabricacao',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('cor',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('placa',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('renavam',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.alter_column('foto_perfil',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('foto_crlv',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('carro_marca')
        batch_op.drop_column('carro_modelo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carro_modelo', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('carro_marca', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('foto_crlv',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('foto_perfil',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('renavam',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('placa',
               existing_type=sa.String(length=7),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('cor',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('ano_fabricacao',
               existing_type=sa.String(length=4),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('modelo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('marca',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('oficina_ibfk_1', 'user', ['usuario_id'], ['id'])
        batch_op.alter_column('lon',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('endereco',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('contato')

    # ### end Alembic commands ###
